-- drop all tables
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

-- give access to postgres
GRANT ALL ON SCHEMA public TO pcc;
GRANT ALL ON SCHEMA public TO public;

-- create tables
-- Table Jour
CREATE TABLE IF NOT EXISTS Jour (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(20) NOT NULL UNIQUE
);

-- Table Ligne
CREATE TABLE IF NOT EXISTS Ligne (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

-- Table Frequence
CREATE TABLE IF NOT EXISTS Frequence (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurrence INT NOT NULL,
    dateDebut DATE NOT NULL,
    dateFin DATE NOT NULL,
    heureDebut TIME NOT NULL,
    heureFin TIME NOT NULL,
    sens BOOLEAN NOT NULL,
    ligne INT NOT NULL REFERENCES Ligne(ID) ON DELETE CASCADE
);

-- Table association Frequence - Jour (s'applique)
CREATE TABLE IF NOT EXISTS Frequence_Jour (
    frequence INT NOT NULL REFERENCES Frequence(ID) ON DELETE CASCADE,
    jour INT NOT NULL REFERENCES Jour(ID) ON DELETE CASCADE,
    PRIMARY KEY (frequence, jour)
);

-- Table Station
CREATE TABLE IF NOT EXISTS Station (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

-- Table LigneStation
CREATE TABLE IF NOT EXISTS LigneStation (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordre INT NOT NULL,
    ligneID INT NOT NULL REFERENCES Ligne(ID) ON DELETE CASCADE,
    stationID INT NOT NULL REFERENCES Station(ID) ON DELETE CASCADE,
    UNIQUE (ligneID, ordre),
    UNIQUE (ligneID, stationID)
);

-- Table Trajet
CREATE TABLE IF NOT EXISTS Trajet (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    ligne INT NOT NULL REFERENCES Ligne(ID) ON DELETE CASCADE
);

-- Table Horaire
CREATE TABLE IF NOT EXISTS Horaire (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateArriveeTheorique TIMESTAMP NOT NULL,
    dateArriveeReelle TIMESTAMP,
    dateDepartTheorique TIMESTAMP NOT NULL,
    dateDepartReelle TIMESTAMP,
    trajet INT NOT NULL REFERENCES Trajet(ID) ON DELETE CASCADE,
    ligneStation INT NOT NULL REFERENCES LigneStation(ID) ON DELETE CASCADE
);

-- Table Train
CREATE TABLE IF NOT EXISTS Train (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vitesse FLOAT NOT NULL,
    dateArriveePosition TIMESTAMP NOT NULL
);

-- Table ElementVoie
CREATE TABLE IF NOT EXISTS ElementVoie (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    longueur INT NOT NULL,
    elementSuivant INT REFERENCES ElementVoie(ID) ON DELETE SET NULL
);

-- Table association Train - ElementVoie (est positionné sur)
CREATE TABLE IF NOT EXISTS Train_ElementVoie (
    train INT NOT NULL REFERENCES Train(ID) ON DELETE CASCADE,
    elementVoie INT NOT NULL REFERENCES ElementVoie(ID) ON DELETE CASCADE,
    PRIMARY KEY (train, elementVoie)
);

-- Table Incident
CREATE TABLE IF NOT EXISTS Incident (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    dateDebut TIMESTAMP NOT NULL,
    dateFin TIMESTAMP,
    trajet INT NOT NULL REFERENCES Train(ID) ON DELETE CASCADE
);

-- Table association Trajet - Train (fait partie d'un)
CREATE TABLE IF NOT EXISTS Trajet_Train (
    trajet INT NOT NULL REFERENCES Trajet(ID) ON DELETE CASCADE,
    train INT NOT NULL REFERENCES Train(ID) ON DELETE CASCADE,
    PRIMARY KEY (trajet, train)
);

-- Table Utilisateur
CREATE TABLE IF NOT EXISTS Utilisateur (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    motDePasse VARCHAR(255) NOT NULL
);

-- Table Itineraire
CREATE TABLE IF NOT EXISTS Itineraire (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur INT NOT NULL REFERENCES Utilisateur(id),
    date TIMESTAMP NOT NULL,
    depart BOOLEAN NOT NULL,
    stationDepart INT NOT NULL REFERENCES Station(id),
    stationArrivee INT NOT NULL REFERENCES Station(id)
);

-- Insertion stations
INSERT INTO Station (nom) VALUES
    ('Pointe du Lac'),
    ('Créteil'),
    ('Université'),
    ('L''Échat');

-- Insertion trains
INSERT INTO Train (vitesse, dateArriveePosition) VALUES
    (80.5, '2025-12-19 08:00:00'),
    (75.0, '2025-12-19 08:05:00'),
    (85.3, '2025-12-19 08:05:00'),
    (78.2, '2025-12-19 08:05:00');

-- Insertion jours
INSERT INTO Jour (id, nom) VALUES
    (1, 'Lundi'),
    (2, 'Mardi'),
    (3, 'Mercredi'),
    (4, 'Jeudi'),
    (5, 'Vendredi'),
    (6, 'Samedi'),
    (7, 'Dimanche');

INSERT INTO Ligne (id, nom) VALUES (1, 'Ligne 8');

-- Insertion fréquences
INSERT INTO Frequence (id, recurrence, dateDebut, dateFin, heureDebut, heureFin, sens, ligne) VALUES
    (1, 10, '2025-12-15', '2026-12-10', '08:00:00', '22:00:00', true, 1),
    (2, 2, '2025-12-15', '2026-12-10', '22:00:00', '23:00:00', true, 1);

INSERT INTO Frequence_Jour (frequence, jour) VALUES
    (1, 5),
    (2, 5);

